### PR TITLE
idempotent datetime(datetime)

### PR DESCRIPTION
**Pull request by scivision**
this is useful when casting to datetime in a function, to avoid an
extra if clause.

### CODE REVIEW

**Comment by apjanke** [comment]
Oh, this is a good idea! `datetime()` should totally be idempotent. And we probably need this for Matlab compatibility anyway.

I think the right implementation is probably something like this, though, to avoid unnecessary computations, and preserve the TimeZone and Format properties of the input:

```
if isa(x, 'datetime')
  out = x; % and maybe we should cast subtypes up to the base @datetime type?
  return;
elseif isnumeric (x) || isdatetime(x) % this'll catch anything that says yes to isdatetime() but isn't actually a @datetime object
  dnums = datenum (x);
...
```

Could I talk you in to breaking up the behavior change and the whitespace formatting changes into two separate commits, to make the diff easier to view?

**Comment by apjanke** [comment]
Lookin' good! I'm cool to merge this if you're happy with where it's at.

**Comment by scivision** [comment]
Hmm, this new way returns `NaT` which is not desired

**Comment by scivision** [comment]
yes this works

**Comment by apjanke** [comment]
Ohmigosh, I forgot about this PR and let it sit around forever. Sorry about that!

Two things:
* There's a lot of whitespace-only changes here. Could you remove those, to make the diff ore readable and avoid dirtying the git commit/blame history?
* Merge conflict. Can you rebase on master?

**Comment by apjanke** [comment]
Hmm. Still a lot of whitespace-only changes here. I'm having a hard time reviewing this.

**Comment by apjanke** [comment]
Did this in https://github.com/apjanke/octave-tablicious/commit/bf1db6c9b58d240dfe8d73634dde07b493133262, including idempotent constructors for most of the other classes in Tablicious. (But not `table`.)

Sorry for not merging your PR and giving you author credit here; just had too much trouble sorting out the merge, and I was impatient to get this in to the code base for the 0.4.0 release.

**Pull request closed without merging**
