### PR TITLE
docs: refresh code of conduct, fix email address

### PR DESCRIPTION
**Pull request by mtmiller**
Same as the others!

### CODE REVIEW

**Comment by mtmiller** [comment]
gentle ping :sparkles:

**Comment by mtmiller** [comment]
@apjanke ping :sparkles: I suspect you may not have notifications turned on for this repo :grin:

**Comment by apjanke** [comment]
You're right, Watch was off! I wonder what else I missed; I'll go through and check the Issues now.

**Comment by apjanke** [comment]
Merged. Thank you!

**Pull request merged**
